// End Points for Categories
// GET: api/categories
// GET: api/categories/{id}
// GET: api/categories/by-slug/{slug}
// POST: api/categories
// PUT: api/categories/{id}
// DELETE: api/categories/{id}

###
GET http://localhost:5279/api/categories

###
GET http://localhost:5279/api/categories/1

###
GET http://localhost:5279/api/categories/by-slug/test-category

###
POST http://localhost:5279/api/categories
Content-Type: application/json

{
    "Name": "Electronics",
    "Slug": "electronics"
}

###
PUT http://localhost:5279/api/categories/1
Content-Type: application/json

{
    "Name": "Updated Category",
    "Slug": "updated-category"
}

###
DELETE http://localhost:5279/api/categories/2




