// http request for lecture
GET http://localhost:5279/api/lectures


###
// http request for create lecture
// string Title, string Description, string VideoUrl, string ImageUrl, string AuthorId)

POST http://localhost:5279/api/lectures
Content-Type: application/json

{
    "Title": "Test Lecture",
    "Description": "Test Description",
    "VideoUrl": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "ImageUrl": "https://via.placeholder.com/150",
    "AuthorId": "1"
}
